version: '3.8'

services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - frontend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongo
    volumes:
      - ./backend:/app
    
    networks:
      - backend

  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data
  #   env_file:
  #     - example.env

networks:
  frontend:
  backend:

